.github/workflows/go.yml

- Adds github workflow to lint, fmt, and test on push

Add github workflow

---

.circleci/config.yml

**What**
- Use circleci because github actions are just too buggy right now

Add a circleci configuration

---

README.md
pkg/crypto/encrypt.go
pkg/data/managers/base.go
pkg/data/managers/base_test.go
pkg/data/managers/id_resolver.go
pkg/db/names.go
pkg/db/open.go
pkg/db/serialization/json_blob.go
pkg/fileutils/list.go
pkg/tracing/tracer.go
pkg/validation/rules.go
tools/tools.go

**What**
- Revisited all the comments and improved them
- Added unit tests for `BaseManager.GetPageInfo`
- Removed unused files
- Changed Readme

Improve documentation and tests

---

go.mod
go.sum
pkg/db/serialization/json_blob.go
pkg/db/serialization/json_blob_test.go
pkg/db/serialization/serializable.go
pkg/http/middlewares/cors.go
pkg/http/middlewares/cors_test.go
pkg/http/middlewares/hostname.go
pkg/http/middlewares/logging.go
pkg/http/middlewares/logging_test.go
pkg/http/middlewares/metrics.go
pkg/http/middlewares/metrics_test.go
pkg/http/middlewares/middleware_test.go
pkg/http/middlewares/path.go
pkg/http/middlewares/recovery.go
pkg/http/middlewares/recovery_test.go
pkg/http/middlewares/tracing.go
pkg/http/middlewares/tracing_test.go

**What**
- Fixed code to have `package middlewares` in `pkg/http/middlewares`
- Fixed code to have `package serialization` in `pkg/db/serialization`
- Cleaned up dependencies

Fix incorrect package names

---

README.md
pkg/errors/errors_test.go
pkg/http/middlewares/tracing.go
pkg/validation/rules.go

**What**
- Add status badges for the go docs, goreportcard, and the latest test
status to the readme
- A few comments and typo tweaks to get all 100% from goreportcard

Add test, docs, an goreportcard status badges

---

go.mod
pkg/data/managers/base.go
pkg/data/managers/base_test.go
pkg/data/managers/id_resolver.go
pkg/data/managers/id_resolver_test.go
pkg/db/open.go
pkg/db/test/db.go
pkg/db/tracing.go
pkg/http/handlers/base.go
pkg/http/handlers/base_test.go
pkg/http/middlewares/authorization/middleware.go
pkg/http/middlewares/cors.go
pkg/http/middlewares/cors_test.go
pkg/http/middlewares/logging.go
pkg/http/middlewares/logging_test.go
pkg/http/middlewares/metrics.go
pkg/http/middlewares/metrics_test.go
pkg/http/middlewares/middleware_test.go
pkg/http/middlewares/recovery.go
pkg/http/middlewares/recovery_test.go
pkg/http/middlewares/tracing.go
pkg/http/middlewares/tracing_test.go
pkg/http/parameters/test/resolver.go

Otherwise the module is not valid.

Prepare a major release v2

---

pkg/generators/router/router.go
pkg/generators/router/router_test.go

Now the router always produces results in the same order, so no more
unnecessary diffs after the generation.

Make router generation deterministic

---

.circleci/config.yml
go.mod
go.sum
pkg/generators/models/enums.go
pkg/generators/models/enums_test.go
pkg/generators/models/testdata/model_filter_type.go
pkg/generators/models/testdata/model_highlight_indicator_start.go
pkg/generators/router/router.go
pkg/generators/router/router_test.go
pkg/generators/templates/casing.go
pkg/generators/templates/casing_test.go
pkg/generators/templates/comments.go
pkg/generators/templates/comments_test.go
pkg/http/middlewares/authorization/timestamp.go

**What**
- Add new models package to the generators, this package can read an
openapi spec and output the enums in a _nice_ way.
- Create a templates package inside generators to hold the common
template functions

Initial enum generator

---

pkg/queue/handlers/dispatcher.go
pkg/queue/handlers/dispatcher_test.go

This handler allows to register other handlers and dispatch based on
type of the task in the queue.

Add dispatch task handler

---

pkg/queue/workers/task_worker.go
pkg/queue/workers/task_worker_test.go

Now if task handler returns an error it's set into the task's
progress.
There was a race condition that set task status as `finished` instead
of `failed` sometimes.

Fix race condition and add progress error

---

pkg/queue/mock_test.go
pkg/queue/postgres/scheduler.go
pkg/queue/postgres/scheduler_test.go
pkg/queue/scheduler.go

Now you can use this single function to upsert a schedule.

Add `AssertSchedule` functionality

---

pkg/queue/metrics_test.go
pkg/queue/queue_mock.go

Now it can be used by other services.

Implement the actual queue interface in the queue mock

---

pkg/db/open.go

Gives way more data for debugging.
I misconfigured datastore and tried to create a collection, here is the logs.

Add error logging when connect to a database

---

pkg/http/parameters/pagination.go
pkg/http/parameters/pagination_test.go

So, we can extend page size in certain situations.

Let customize the pagination bounds and default size

---

pkg/queue/postgres/retention.go

**What**
- Add new public method for asserting any retention task. This allows us
to build the task spec in our applciations but still use the generic
assertion code

Add generic retention task assertion

---

pkg/queue/workers/task_worker.go
pkg/queue/workers/task_worker_test.go

**What**
- The worker metrics include a count of errors per queue and type, but
the error being tracked was not the handler errors, so this value was
never set or always 0.
This fixes the error tracking so that the counter works as expected.
This allows the metric to be used in alerts for high error rates on
sensitive queues or task types.
New unit tests were added to ensure this counter works as expected and
I have manually tested this in our IdP service.
Manual tests:
1. I started local dev and then stopped the mail trap using `docker stop dev_smtpmock_1`
2. You can see the failed email task in this screenshot
3. Similarly, yo ucan see that the expected `error` metric is not shown or incremented in the metrics endpoint 
4. After updating IdP to use this branch, I recreated a failed …

fix: Queue worker handler error metric is not set

---

pkg/http/clients/base_api_client.go
pkg/http/clients/base_api_client_test.go

Add new `WithTokenProvider` and a new provider from existing claims.
This allows cloning existing clients, but overriding the token provider.
In practice these methods can be used together to create a new client
bound to an existing set of authorization claims.

feat: Allow cloning API Clients with new token providers

---

pkg/http/clients/base_api_client.go
pkg/http/clients/base_api_client_test.go

Now there is `.WithHeader` function that can be used for setting
additional custom headers for an API HTTP request.
Verified in https://github.com/contiamo/idp/pull/641

feat: add support for setting headers in API client

---

pkg/http/clients/base_api_client.go
pkg/http/clients/base_api_client_test.go

The default base api client could result in nearly infinite retry of
requests, due to a rollover of the uint64 from 0 to `18446744073709551615`
when doing `c.maxAttempts-1`
Now, we only shift the attempts number _if_ it is greater than zero,
defaulting the intended behavior: no retry.

fix: do not allow infinite retry by default in the base api client

---

go.mod
go.sum

https://github.com/advisories/GHSA-w73w-5m7g-f7qc

feat: update `contiamo/jwt` to fix CVE

---

pkg/config/logging.go

Add utility for the standard logrus configuration

feat: add a standard logging configuration util
