go.mod
go.sum
pkg/http/middleware/metrics.go
pkg/http/middleware/path.go
pkg/http/middleware/tracing.go
pkg/http/middleware/tracing_test.go
pkg/tracing/jaeger.go
pkg/tracing/jaeger_test.go

**What**
- Remove server parameter from the tracing configuration, this value
will now be set by Jaeger's own method via the env
- Add a new path cleaning method that uses Chi mux route lookup so that
we can support name based resolution on its own
Based on #7

Refactor remove server value from tracing int

---

pkg/http/handlers/base.go
pkg/http/handlers/base_test.go

**What**
Because we added more details about JSON parsing errors it broke the
status code reporting.

Fix incorrect 500 when Unmarshalling error

---

go.mod
pkg/validation/rules.go
pkg/validation/rules_test.go

**What**
- We should actually enforce that names are shorter than 64 characters,
postgres will otherwise truncate the last character.

SQL identifier max lenght is 63

---

go.mod
pkg/generators/router/router.go
pkg/generators/router/router_test.go

**What**
Generate writes a `chi` router source code into a given `Writer` reading
the YAML definition of the Open API 3.0 spec from a given `Reader`.
It supports options to set a package name and error behavior.
All included into generation endpoints must have `operationId` and `x-handler-group`
attributes. Depending on the options the generator will either produce an error or skip
endpoints without these attributes.

Add chi router generator

---

pkg/db/serialization/json_blob.go
pkg/db/serialization/json_blob_test.go

**What**
- Expand scan support so that nil and string values are supported, this provides better support for arbitrary blobs, which could be nil, e.g. in a join 

Allow scanning string and nil values from the db

---

pkg/http/middlewares/authorization/claims.go

**What**
- In the pgql server we need to retreive the user claims from an
arbitrary context, not directly from a request object, because the
request context and passed to the required location indirectly. This new helper
supports that

Add help to retreive user claims from ctx

---

pkg/crypto/encrypt.go
pkg/crypto/encrypt_test.go
pkg/crypto/generate.go
pkg/crypto/generate_test.go

Now it's possible to use Authenticated Encryption using
MAC-then-Encrypt (MtE) approach.
Also, now it's easier to create a state or CSRF token using
`GenerateToken` and then verify it using `DecodeAndVerifyToken`.

Add Seal/Unseal and crypto token creation

---

pkg/crypto/encrypt.go

That makes it simpler to embed the value into go templates.

Switch `Seal` to use `Base64.URLEncoding` instead

---

pkg/data/managers/base.go

This optimizes the page info retrieval to only use one query to get `UnfilteredItemCount` and `ItemCount`

only use a single query to get the page infos.

---

pkg/data/managers/base.go
pkg/data/managers/id_resolver.go
pkg/db/builder.go

So, there is no direct dependency to a structure type. It's more
convenient in certain situations for us to have an interface that
can be `nil`.

Introduce `SQLBuilder` interface

---

pkg/data/managers/base.go

This reverts commit aecc07f648dfc55201fe0fcf33bc0390920dca64.
This change breaks the existing code in Hub.

Revert "only use a single query to get the page infos. (#25)"

---

go.mod
pkg/crypto/generate.go
pkg/data/managers/id_resolver.go
pkg/data/managers/id_resolver_test.go
pkg/http/middlewares/authorization/claims.go
pkg/http/middlewares/authorization/claims_test.go
pkg/http/middlewares/path.go

We should be stricter about typing of ID values if we know for sure
that the value is always a UUID. This change breaks backwards
compatibility and requries a major release.
* name -> UUID resolution now always returns a UUID
* claims work with UUIDs instead of strings for all ID values
* removed `github.com/google/uuid` as a direct dependency in `path` middleware.

Replace strings with UUID wherever needed

---

pkg/data/managers/id_resolver_test.go
pkg/db/serialization/null/time.go
pkg/db/test/db.go

**What**
- Allow passing multiple init methods for the test GetDatabase method
- Fix NullTime string formatting consistency

Allow passing multiple init method for GetDatabase

---

pkg/db/open.go

**What**
- Set the db pool max open connections limit as soon as we open the db
this ensures the value is always set

Ensure Max open connections is set during open

---

go.mod
go.sum
pkg/db/open.go

There was a missing error check and the connection was checked before
breaking out of the backoff loop.

Check error and use `Ping` in `db.Open`

---

pkg/http/handlers/base.go
pkg/tracing/stdout.go

**What**
- Add new BaseHandler factory method that allows passing a preconfigured
Tracer
- Add a new Tracer that wraps the opentracing spans with logs
- Add helper utilities for extracting the trace id and span id from
jaeger Spans

Allow configuring tracer in BaseHandler, add logging tracer

---

go.mod
go.sum
pkg/config/queue.go
pkg/queue/manager.go
pkg/queue/manager_test.go
pkg/queue/metrics.go
pkg/queue/mock_test.go
pkg/queue/postgres/dequeuer.go
pkg/queue/postgres/dequeuer_test.go
pkg/queue/postgres/fixtures_test.go
pkg/queue/postgres/queuer.go
pkg/queue/postgres/queuer_test.go
pkg/queue/postgres/scheduler.go
pkg/queue/postgres/scheduler_test.go
pkg/queue/postgres/setup.go
pkg/queue/postgres/setup_test.go
pkg/queue/scheduler.go
pkg/queue/scheduler_test.go
pkg/queue/task.go
pkg/queue/workers/metrics.go
pkg/queue/workers/schedule_worker.go
pkg/queue/workers/schedule_worker_test.go
pkg/queue/workers/task_worker.go
pkg/queue/workers/task_worker_test.go
pkg/queue/workers/worker.go

Changes in order to make this generic:
* change imports
* add `postgres.Setup()` function which bootstraps the db (this has parameters)
* as a side effect of this the metrics are setup with a usage specific namespace
* the metrics setup is now a bit more complex as it takes a parameter and therefore needs to be called instead of just being global variables
* there are several minor test changes + some new tests to show that the argument propagation works for the setup.

add queue code.

---

pkg/generators/models/enums.go
pkg/generators/models/testdata/model_highlight_indicator_start.go

**What**
- Generate a Go `const` if the enum values has exactly one element
- See https://github.com/OAI/OpenAPI-Specification/issues/1313 and
https://github.com/OAI/OpenAPI-Specification/issues/1620 as examples
where the openapi team blessed the "singleton enum" example

Generate const if enum has exactly one element

---

pkg/queue/manager_test.go
pkg/queue/metrics.go
pkg/queue/postgres/dequeuer_test.go
pkg/queue/postgres/queuer_test.go
pkg/queue/postgres/scheduler_test.go
pkg/queue/postgres/setup.go
pkg/queue/postgres/setup_test.go
pkg/queue/workers/schedule_worker_test.go

* There are now default metrics, so the queue does not panic in runtime.
* The namespace of the metrics can be easily switched by calling `SwitchMetricsNamespace`, (executed binary name  by default)
* `Setup` function is renamed to `SetupTables` because that's what it's supposed to do.

Change the way queue metrics are initialized

---

pkg/queue/metrics.go
pkg/queue/metrics_test.go

When switch queue metrics to the same name it caused panic in the
Prometheus client we use. Now we properly unregister the previous collectors.

Fix panic when switch to the same service name

---

pkg/queue/postgres/scheduler.go
pkg/queue/postgres/scheduler_test.go
pkg/queue/workers/schedule_worker_test.go

Sometimes it's needed to create a job that executes once.

Allow one-time jobs in the scheduler

---

pkg/queue/postgres/setup.go
pkg/queue/postgres/setup_test.go
pkg/strings/casing.go
pkg/strings/casing_test.go

Now it's possible to change both:
* list of system columns in `tasks` and `schedules`
* list of user defined references of the queue item
Only adding or removing of columns is supported, once it's created
it's not going to be edited only dropped if removed from the list.
Also, added some string functions for casing conversions.

Add support for changing references in the queue

---

pkg/strings/casing.go
pkg/strings/casing_test.go

* `created_at DESC` -> `created_at_desc`
* de-duplication of underscore characters.

Support more cases for underscore casing conversion

---

pkg/db/test/db.go
pkg/queue/postgres/setup.go
pkg/queue/workers/retention.go
pkg/queue/workers/retention_test.go
pkg/queue/workers/sql_task.go
pkg/queue/workers/sql_task_test.go

**What**
- Create a new task handler that can be used to cleanup old tasks
matching a specific filter. The caller can specify the queue, task
type, status, age, and a custom sqlizer.
- Add utility to schedule this new cleanup task once per hour. The exact
minute is chosen randomly as a basic attempt to spread our the
workload.
- Improve the db test utility EqualCount to allow passing an error
message and ars down to the require method inside of it. This allows
the errors to be more expressive and hopefully easier to read
- Add new db setup utility that uses docker to ensure a db server is
ready. This is intended as a dev mode only tool which is not left in
the final committed code, but can be very useful to speedup test
iteration and debugging.
Signed-off-by: Lucas Roesler …

Create task retention worker and scheduler

---

go.mod
go.sum
pkg/crypto/hash.go
pkg/crypto/hash_test.go

add Hash() and HashToString() function to the crypto package to have one standard way of hashing across different projects.
I would like to add those two functions and the implementation to the crypto package, so we don't have to write these things again in different projects. 
I think the `Hash(args ...interface{}) ([]byte, error)` signature will fit all our needs and the implementation supports io.Reader, string, bytes and as a fallback all json-marshalable data types. Also we can easily swap out the used hashing algorithm which is currently `sha3` but I'm open to feedback and we could change it to something more conservative without any effort.

add Hash() and HashToString() function to the crypto package

---

pkg/queue/workers/retention_test.go
pkg/queue/workers/sql_task.go

**What**
- Ensure that the task actually ends by closing the heartbeats channel.
This was not seen during previous testing because the test code closed
the channel. However, when deployed, the task never finished.

Close heartbeats in the sql task handler

---

pkg/queue/handlers/dispatcher.go
pkg/queue/handlers/dispatcher_test.go

This will unblock the queue in case the task type is not handled by anything.

Close heartbeats in dispatcher when unknown task type

---

pkg/queue/postgres/retention.go
pkg/queue/postgres/scheduler.go
pkg/queue/postgres/setup.go
pkg/queue/postgres/setup_test.go

**What**
- When depeloying some of the apps with the retention policy, we saw the
startup get stuck during the retention task assertion. Moving a an
INSERT ON CONFLICT upsert method avoids the table lock and has the
same effect.
- Add a partial unique index to the schedules table that is required for
the upsert flow
- Any project using the retention policies will need to add this
migration to their startup
```sql
CREATE UNIQUE INDEX IF NOT EXISTS unique_retention_idx
ON schedules (task_queue, task_type, (task_spec->>'queueName'), (task_spec->>'taskType'), (task_spec->>'status'))
WHERE task_type = 'retention';
```

Use INSERT ON CONFLICT for retention task upsert

---

pkg/http/middlewares/authorization/claims.go
pkg/tokens/creator.go
pkg/tokens/creator_test.go

* Now the issuer is not hard-coded as `hub` anymore
* The claims have the new `AuthenticationMethodReferences` to make it
work with IdP

Enable token issuer customization and add auth method references

---

.circleci/config.yml
pkg/queue/workers/task_worker.go
pkg/queue/workers/task_worker_test.go

**What**
- During the worker iteration, return after the task handler returns.
This stops the iteration span and allows the worker to start a new
iteration. This will avoid having multiple task spans inside the same
iteration span.

Return after task is handled

---

pkg/tracing/logrus.go
pkg/tracing/logrus_test.go

**What**
- Implement `SpanHook` that can write logrus Entries to the current span
logs. This unifies the log interface in our projects

Implement logrus hog to log to spans

---

pkg/tracing/logrus.go
pkg/tracing/logrus_test.go

**What**
- During the span hook, we copy the log to the span, this patch also
copies the span and trace id to the log so that tools like Grafana can
correlate log lines back to the traces. This works in two steps
First, configure the span hook during server init
```go
logrus.AddHook(&tracing.SpanHook{})
```
Then, while logging use `logrus.WithContext(ctx)`

Add tracing ids to log fields via the span hook

---

pkg/testing/json.go
pkg/testing/json_test.go

**What**
- To simplify some of the tests checks, it can be helpful to allow
matches on two empty strings, even though neither is valid json.
Specifically this helps when testing apis that can return errors
and 204 empty body.
Tests provide 100% lines coverage of the new method

Implement JSONEq that allows matches on empty string

---

go.mod
pkg/data/managers/base.go

This allows to get page information to an arbitrary query.
Since the new function is now used by the previous one, the existing unit tests fully cover the new behavior.

Add `GetPageInfoWithQuery` to make the interface more convenient

---

pkg/queue/postgres/retention.go
pkg/queue/postgres/retention_test.go
pkg/queue/workers/schedule_worker.go

**What**
- Do not mix the use of the sql `NOW` and the server `time.Now` when we
have time sensitive calculations. This specifically avoids issues
where the server time drifts behind the DB time, it can cause crons to
be rescheduled immediately because (from the server persepective) they
are being scheduled too early

Avvoid time drift issues during cron scheduling

---

.gitignore
pkg/http/middlewares/authorization/middleware.go
pkg/http/middlewares/authorization/middleware_test.go

**What**
- Implement an explicit sanitization of the header value before we log
it to the tracing tags. This make it clear that we we not leaking
sensitive data

Explicitly sanitize the auth header value in tracing

---

pkg/queue/handlers/api_request.go
pkg/tokens/creator.go
pkg/tokens/creator_mock.go
pkg/tokens/creator_test.go

**What**
- Refactor the creator interface to always geneate inter-service tokens.
- Add the `aud` field (Audience) to the token claims
- Add the `azp` field (AuthorizedParty) to the token claims
- Pass the project and the audiance via a new `tokens.Options` struct,
this makes it easier to update the interface in the future.
- This allows us to avoid re-using authorization concepts like the
project admin when communicating between services, we can now be more
explicit that the request represents a specific service via the `azp`
value.

Refactor tokens Creator interface

---

go.mod
go.sum
pkg/http/handlers/base.go
pkg/http/handlers/base_test.go

- Allow the base http handler to handle validation errors
from ozzo v1 and ozzo v4. The new v4 handling allows the
base handler to support the generated validators from
openapi-generator-go:
https://github.com/contiamo/openapi-generator-go
I needed this as part of the upgrade to the new generator in datastore, some of the handlers were returning 500s where it was previously returning 422, with this change, they return 422 again.

feat: Suppor ozzo v4 validation errors in the base handler

---

pkg/http/middlewares/authorization/middleware.go

**What**
- When the logging was previously refactored in the authorization
middleware, the `prettyRequest` was being logged as a raw bytes
array, which is impossible to read. This change converts it to a
string so that the log is readable.
Found while testing CON-3026

fix: during authn errors print req object as string

---

pkg/http/clients/base_api_client.go
pkg/http/clients/base_api_client_test.go

Can be used to easily perform HTTP requests to various JSON
APIs. Also, it's going to be used in the code generator.

Add `BaseAPIClient`

---

pkg/db/migrations/migrations.go

**What**
- Add more logging so that users can see the run or skip message for all
migration statements. Additionally, add a few more log statements to
ensure all possible errors are logged as soon as possible

fix: Add more logging during db migrations

---

pkg/db/migrations/migrations.go

Use a named return in the `migrate` method so that the error from
`err = tx.Commit()` is correctly ghosting the return value and therefore
actually returned to the calling method

fix: Use named return to ensure migration commit err is returned

---

Makefile
pkg/db/migrations/migrations.go

Catch and ignore `pq: unexpected transaction status idle` errors when we
commit the migrations transaction.  We have not see the error in
practice when testing the recent changes to the migrations _but_ we do
see this in the unit tests for Hub. This error indicates that a
transaction has started, ie `BEGIN;` but that nothing has happened in
the transaction yet. A similar (but resolved) issue happened in the pq
driver, but the culprit (unclosed Rows) does not apply to our method,
all possible Row objects are automatically closed for us by the sql
methods. See https://github.com/lib/pq/issues/225
See also
https://www.postgresql.org/message-id/20080617133250.GA68434@commandprompt.com

fix: Do not throw errors for idle transactions during migration

---

.github/workflows/conventional-commits.yaml
.github/workflows/release-please.yaml

**What**
- Add workflow that enfoces conventional commits on our PR titles
- Add workflow that automates creating releases. It opens a PR with
the new changelog. The PR will be kept up-to-date as more merges
happen.  When merged a tag/release is automatically created.
- Remove release changelog management from jenkins

ci: Automate release workflow

---

.github/dependabot.yml

ci: add github-actions to dependabot

ci: fix dependabot config to support conventional commits

---

pkg/errors/errors.go
pkg/http/handlers/base.go
pkg/http/handlers/base_test.go

Add a new error `ErrUnsupportedMediaType` and handling for this error in
the BaseHandler implementation. This allows for endpoints that support
multiple content types to test and return an appropriate standard
response if the request is not supported.

feat: Add error handling for Unsupported Media Type

---

pkg/http/clients/base_api_client.go
pkg/http/clients/errors.go
pkg/http/clients/errors_test.go

No the `APIError` struct implements all the edge cases of error
reporting and simplifies how we handle error responses.

fix: make API errors more informative, no empty strings

---

pkg/http/clients/base_api_client.go
pkg/http/clients/base_api_client_test.go

When an JSON api responses with 204 No Content, the BaseAPIClient
implementation would still attempt to parse the response body. But this
just throws and EOF error. When the API is responding with 204 this is
actually expected and the caller should/will pass a `nil` value to the
`out` parameter. The client implementation will now skip parsing the
body if the `out` destination is nil.

fix: do not parse body if ouput dest is nil

---

pkg/data/managers/id_resolver.go
pkg/data/managers/id_resolver_test.go

Before this change we would accept any valid UUID in the id resolver without database interaction. This caused CON-3568 where its possible to retrieve a table by id using a URL with a wrong data source id.
Now the resolver actually looks up the id, if its a valid uuid, under the given filter, so we return an error when the id is not actually found in the database.

feat(CON-3568): check that ids exist under a filter when resolving.

---

pkg/errors/errors.go
pkg/errors/errors_test.go

Before this change the sorting of the field errors was not deterministic because we only sorted by message. So if you have for example an error with two wrong enums, you get the same message but different keys. Now the order of those two errors is unfortunatly random. 
Now I look if the errors have a GetKey() function and if they have I use it for sorting, if not I fallback to the message.

fix: sort field errors not only by message, but by key (if any) and then by message

---

pkg/errors/error_response.go
pkg/errors/errors_test.go

I thought that the FieldError type comes from our generator, because it already had getters for Type and Message. This was wrong so I was expecting that GetKey() also exists, but in fact it doesn't. 
This commit now adds the GetKey() method, so that the key is correctly picked up when sorting.
I adjusted the unit test so that both error messages are the same, so that it really would be non-deterministic if not sorted by key.

fix: add missing GetKey() function for FieldErrors.

---

pkg/http/clients/base_api_client.go

Add the `DoRequstWithResponse` method to the `BaseAPIClient` to enable advanced use cases
that are not just the standard JSON REST API calls.
We will use this for a method that just wants to copy the response to
another Writer. Having direct access to the Response body provides the
least overhead.

feat: Add request method to BaseAPIClient that expose the response object

---

go.mod
go.sum
pkg/config/jwt.go
pkg/config/jwt_test.go
pkg/http/middlewares/authorization/middleware.go
pkg/http/middlewares/authorization/middleware_test.go
pkg/tokens/creator.go
pkg/tokens/creator_test.go

Move from github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt. The
owner decided to move the development into a separate org and to invite
more maintainers. This version bump also includes a high severity
security fix for https://github.com/contiamo/go-base/security/dependabot/go.mod/github.com%2Fdgrijalva%2Fjwt-go/open

fix: upgrade JWT library

---

pkg/db/migrations/base.go
pkg/db/migrations/init.go
pkg/db/migrations/migrations.go
pkg/db/migrations/prepare.go
pkg/db/migrations/views.go

Using pg_advisory_lock allows us to block multiple application instances
from running migrations at the same time. The current implementation
uses a table lock, but this requires using transactions, which we have
seen behave oddly. This approach allows us to avoid one large global
transaction and we can move the transaction to wrap each individual
statement instead of the entire process.

feat: use pg_advisory_lock to control db migration concurrency

---

pkg/db/migrations/base.go
pkg/db/migrations/init.go
pkg/db/migrations/migrations.go
pkg/db/migrations/prepare.go

This reverts commit fcea24bd94f459af6bbb6a3997ce5e1a6ebdf6bc.
None of the new pods that use this logic can connect to the database on dev.

fix: Revert "feat: use pg_advisory_lock to control db migration concurrency (#165)"

---

pkg/db/tracing.go
pkg/db/tracing_test.go

So, we don't exceed the UDP frame limit and don't receive errors from
Jaeger on long SQL queries like data ingestion.

feat: add option for trimming SQL in open tracing spans

---

pkg/contexts/signals.go

Add a contexts package that exposes a WithSignals method. This creates a
context that is bound to the passed signals. If no signals are passed,
then it binds to the os.Interrupt by default.

feat: add contexts package to simplify signal handling

---

.github/workflows/ci.yaml
.github/workflows/conventional-commits.yaml
pkg/http/middlewares/metrics_test.go

Change the default branch name from master to main

ci: update ci workflows to reference main

---

pkg/otel/tracing/span.go

Add utility to simplify error handling and ending a span.

chore: add EndSpan utility

---

pkg/http/middlewares/logging.go
pkg/http/middlewares/logging_test.go
pkg/http/middlewares/middleware_test.go
pkg/http/middlewares/tracing.go

Provide configuration points to allow application to skip logging on specific requests. Additionally, allow configuration of the log fields as well.
The change should be backwards compatible, because we previously returned an interface, instead of the concrete type. The type still implements the required interface.

feat: allow skipping http loggin per request

---

pkg/errors/errors.go
pkg/http/handlers/base.go
pkg/http/handlers/base_test.go

Expose the default Handler implementation and allow customizing the error parsing by passing a new parser function. This allows overriding the error handling but with a reasonable default.
Additionally, change `ValidationErrorsToFiedErrorResponse` signature to accept any `map[string]error`. This is the underlying type for a `validation.Error`, so it is backwards compatible, but it is also more flexible and will accept more type aliases for validation errors, making it easier to use.

feat: allow customizing http handler error parsing
